name: Killer on the Loose
main: com.ftwinston.KillerMinecraft.Modules.KillerOnTheLoose.Plugin
depend: [Killer Minecraft]
version: 1
load: STARTUP
description: A game mode for Killer Minecraft
author: FTWinston